# ==============================================
# 班主任班级管理平台 - 使用 Traefik 的 Docker Compose 配置
# ==============================================

services:
  # Traefik 反向代理和自动 HTTPS
  traefik:
    image: traefik:v3.2
    container_name: class-tool-traefik
    restart: unless-stopped
    ports:
      - '80:80'
      - '443:443'
      - '8080:8080' # Traefik Dashboard (可选)
    volumes:
      # Docker socket 用于自动发现服务
      - /var/run/docker.sock:/var/run/docker.sock:ro
      # Traefik 配置文件
      - ./traefik.toml:/etc/traefik/traefik.toml:ro
      # Let's Encrypt 证书存储
      - ${DATA_DIR:-./data}/letsencrypt:/letsencrypt
    networks:
      - app-network
    labels:
      # 启用 Traefik 自身管理
      - 'traefik.enable=true'
      # Dashboard 配置 (可选，用于监控)
      - 'traefik.http.routers.traefik.rule=Host(`traefik.${DOMAIN:-localhost}`)'
      - 'traefik.http.routers.traefik.entrypoints=websecure'
      - 'traefik.http.routers.traefik.tls.certresolver=letsencrypt'
      - 'traefik.http.routers.traefik.service=api@internal'
      # Dashboard 认证 (使用 htpasswd 生成)
      # 默认用户名: admin, 密码: admin (生产环境务必修改)
      # 生成命令: echo $(htpasswd -nb admin your-password) | sed -e s/\\$/\\$\\$/g
      - 'traefik.http.routers.traefik.middlewares=auth'
      - 'traefik.http.middlewares.auth.basicauth.users=admin:$$apr1$$8EVjn/nj$$GiLUZqcbueTFeD23SuB6x0'

  # PostgreSQL 数据库服务
  postgres:
    image: postgres:16-alpine
    container_name: class-tool-postgres-prod
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB:-class_tool}
      POSTGRES_INITDB_ARGS: '-E UTF8 --locale=C'
    volumes:
      # 数据库数据持久化 - 映射到本地目录
      - ${DATA_DIR:-./data}/postgres:/var/lib/postgresql/data
      # 备份目录
      - ./backups:/backups
    ports:
      - '${POSTGRES_PORT:-5432}:5432'
    networks:
      - app-network
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${POSTGRES_USER:-postgres}']
      interval: 10s
      timeout: 5s
      retries: 5
    command:
      - 'postgres'
      - '-c'
      - 'max_connections=200'
      - '-c'
      - 'shared_buffers=256MB'
      - '-c'
      - 'effective_cache_size=1GB'

  # Next.js 应用服务
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: class-tool-app-prod
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      NODE_ENV: production
      DATABASE_URL: postgresql://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB:-class_tool}?schema=public
      BETTER_AUTH_SECRET: ${BETTER_AUTH_SECRET}
      BETTER_AUTH_URL: ${BETTER_AUTH_URL:-https://${DOMAIN}}
      NEXT_PUBLIC_APP_URL: ${NEXT_PUBLIC_APP_URL:-https://${DOMAIN}}
      PORT: ${PORT:-3000}
    volumes:
      # 上传文件持久化 - 映射到本地目录
      - ${DATA_DIR:-./data}/uploads:/app/uploads
    networks:
      - app-network
    healthcheck:
      test: ['CMD', 'wget', '--quiet', '--tries=1', '--spider', 'http://localhost:3000/api/health']
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    labels:
      # 启用 Traefik
      - 'traefik.enable=true'
      # 路由规则
      - 'traefik.http.routers.class-tool.rule=Host(`${DOMAIN:-localhost}`)'
      - 'traefik.http.routers.class-tool.entrypoints=websecure'
      - 'traefik.http.routers.class-tool.tls.certresolver=letsencrypt'
      # 负载均衡配置
      - 'traefik.http.services.class-tool.loadbalancer.server.port=3000'
      # 安全头部中间件
      - 'traefik.http.routers.class-tool.middlewares=security-headers'
      - 'traefik.http.middlewares.security-headers.headers.stsSeconds=31536000'
      - 'traefik.http.middlewares.security-headers.headers.stsIncludeSubdomains=true'
      - 'traefik.http.middlewares.security-headers.headers.stsPreload=true'
      - 'traefik.http.middlewares.security-headers.headers.forceSTSHeader=true'

# 注意: 使用本地目录映射,不再需要 Docker volumes
# 所有数据将存储在 ${DATA_DIR:-./data} 目录下
# - postgres: ${DATA_DIR}/postgres
# - uploads: ${DATA_DIR}/uploads
# - letsencrypt: ${DATA_DIR}/letsencrypt (SSL 证书)

networks:
  app-network:
    driver: bridge
